///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  Assets._();

  static const String fontsNotoSansKRBlack = 'asset/fonts/NotoSansKR-Black.otf';
  static const String fontsNotoSansKRBold = 'asset/fonts/NotoSansKR-Bold.otf';
  static const String fontsNotoSansKRLight = 'asset/fonts/NotoSansKR-Light.otf';
  static const String fontsNotoSansKRMedium = 'asset/fonts/NotoSansKR-Medium.otf';
  static const String fontsNotoSansKRRegular = 'asset/fonts/NotoSansKR-Regular.otf';
  static const String fontsNotoSansKRThin = 'asset/fonts/NotoSansKR-Thin.otf';
  static const String foodDdeokBokGi = 'asset/img/food/ddeok_bok_gi.jpg';
  static const String foodPizzaDdeokBokGi = 'asset/img/food/pizza_ddeok_bok_gi.jpg';
  static const String iconHome = 'asset/svg/icon/home.svg';
  static const String iconOrders = 'asset/svg/icon/orders.svg';
  static const String iconProfile = 'asset/svg/icon/profile.svg';
  static const String iconSearch = 'asset/svg/icon/search.svg';
  static const String logoCodefactoryLogo = 'asset/img/logo/codefactory_logo.png';
  static const String logoLogo = 'asset/img/logo/logo.png';
  static const String miscLogo = 'asset/img/misc/logo.png';
  static const String riveBasketball = 'asset/rive/basketball.riv';
}
